---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ZhouHR.
--- DateTime: 2020/11/26 17:49
---
-- test_module.lua 文件
-- module 模块为上文提到到 module.lua
require("module")

print(module.constant)

module.func3()